from enum import Enum

class TranscriptStatus(str, Enum):
    PENDING = "PENDING"
    FETCHING_AUDIO = "FETCHING_AUDIO"
    PRE_PROCESSING = "PRE_PROCESSING"
    PROCESSING = "PROCESSING"
    TRANSCRIBING = "TRANSCRIBING"
    EMBEDDING = "EMBEDDING"
    CLEANING = "CLEANING"
    SUMMARIZING = "SUMMARIZING"
    DONE = "DONE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"